### ISSUE TITLE
Enforcing .jsx extension for React files

### ISSUE THREAD

**Issue by vinay0x** [bigbinary/wheel#444]
.jsx and .js extensions help in distinguishing React component files from helper files and standard js files. It also helps some editors to identify which formatter/IntelliSense to use for which files. 

It could also help in distinguishing files on first look 
![image](https://user-images.githubusercontent.com/10897109/99616983-51982400-2a44-11eb-90dc-7fe5d0074847.png)

Currently in most of our repos, it's mix. Some people use .jsx for React and some use .js. We could enforce the use of .jsx throughout. 

If this sounds good, I can add this ESLint plugin that'll enforce this.
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md

@neerajdotname what are your thoughts?

**Comment by neerajdotname** [comment]
@vinay0x Is that really helpful. The other solution is to force everyone to use `.js`.  I'm not advocating for any  position. I'm just highlighting another option.

**Comment by vinay0x** [comment]
It's fine either way. But when people mix and match between .js and .jsx it becomes sub-optimal. We can enforce either one style.

**Comment by neerajdotname** [comment]
@vinay0x ok let's go with the first option.

**Comment by edwinbbu** [comment]
@neerajdotname @vinay0x I would like enforcing `.js`. Having both `.js` and `.jsx` in the client side makes in look cluttered.

**Comment by neerajdotname** [comment]
@edwinbbu ok. Fine with me. Go ahead.

**Comment by yedhink** [comment]
This is just a personal preference, but I have a different opinion on this.

When working on `nitro-cal` all our files(helpers, react-components) etc were named with `.js`. But once I started using `.jsx` for component files following `wheel`, the following were much more easier for me:

- Navigating between component files and other helper files - specifically fuzzy searching - because all components are named `.jsx` and others where which doesn't make use of `react` is named with `.js`. 
  * Example of a search:- `*.js common` -----> Finds all `common` files like `logger.js` and brings them to the top of search by prioritising the react components directory named `Commons`
- Out of the box `javascriptreact` intellisense attached for `.jsx` files. This includes good syntax highlighting and formatting helpers etc. But if the react files too are named with `.js`, then we might've to set the file association manually in vscode, like so:- 
```json
"files.associations": {
    "*.js": "javascriptreact"
}
```
- Visual cues to navigate faster through the file explorer in vscode. The icons itself are striking:
![Screenshot_20201120_113344](https://user-images.githubusercontent.com/31244999/99765272-b32fbf80-2b24-11eb-9934-b80fd4767787.png)


Initially I thought it would be an overhead to name things separately like with `.jsx` and `.js`. But the benefits I mentioned above over weighs the effort for me and has actually helped me. And it becomes muscle memory after doing it a bit I guess. :smile: 

Again, this only a suggestion from my side.
Thanks

**Comment by vinay0x** [comment]
> then we might've to set the file association manually in vscode

I don't think this is needed. `.js` files are also highlighted without any separate config for me. 
![image](https://user-images.githubusercontent.com/10897109/99768639-21778080-2b2b-11eb-9555-46cc801cdd78.png)

> Visual cues to navigate faster through the file explorer in vscode. The icons itself are striking:

I agree with this and this is what I mentioned in my first comment. But on the second look, it feels like this is the only advantage. 

The proper way to distinguish React components and helper files are by checking casing. React filenames **must** be capitalized.

Let's try out `.js` in wheel and see. If it is fine we'll do the same with other repos.

**Comment by vinay0x** [comment]
Or let's close this issue for now. We'll come back if there's a pressing need.

**Comment by edwinbbu** [comment]
> The proper way to distinguish React components and helper files are by checking casing. React filenames must be capitalized.

I agree 👍

**Comment by yedhink** [comment]
@vinay0x 
@neerajdotname 
@edwinbbu 

Please take a look into this video I made. I think this demo clearly conveys my points on why we should use `.jsx` for react files and `.js`.

https://youtu.be/RZ0Xc4r39ag

Just reopening on the issue, so that you don't miss out this comment notification. You can close the issue if my points don't feel relevant. 

Thanks

**Comment by vinay0x** [comment]
To enable emmet you just have to do this: 
![image](https://user-images.githubusercontent.com/10897109/99772436-ca74aa00-2b30-11eb-903a-5e1f165ec619.png)

Also, `javascript` and `javascript-react` in VSCode does pretty much the same thing. Since syntactic sugars like JSX are so common now, all it's properties are available in the `javascript` language and not just `javascript-react` for VSC.

The community is heavily split when it comes to this decision. So let's go ahead with what we have for now and revisit when it's necessary. 

PS: We will still receive notifs from closed issues.
