### ISSUE TITLE
Issue with the eslint indent rules

### ISSUE THREAD

**Issue by vikas95prasad** [bigbinary/wheel#484]
Unable to commit the following code due to the indentation rules defined in the ESLint config file.

Rule : `"indent": ["error", 2]`

Example,
```
status == "todo"
  ? "red"
  : status == "in_progress"
  ? "blue"
  : "green";
```
OR
```
status == "todo"
  ? "red"
  : status == "in_progress"
    ? "blue"
    : "green";
```

**Comment by yedhink** [comment]
@vikas95prasad _a

I just tried out committing the above suggested example and it got committed without raising any errors.

Please provide exact error that you received with screenshots and also provide the steps to reproduce that particular in this repo `wheel`. Example try to reproduce the same error in `Main.jsx` file in `wheel` by adding your custom code.

**Comment by vikas95prasad** [comment]
@yedhink _a

Here, is the video link: https://www.loom.com/share/7b7ab62a1ebf4a41860e1497e5021c8b 

Try with this code,
```
const badgeColor = status => {
    status == "todo"
      ? "blue"
      : status == "in_progress"
      ? "red"
      : status == "in_review"
      ? "green"
      : status == "in_qa"
      ? "gray"
      : "yellow";
  };
```
<img width="1421" alt="Screenshot 2021-05-05 at 11 52 13 AM" src="https://user-images.githubusercontent.com/16317458/117105743-4b9cc200-ad9c-11eb-9372-5b16cd60ca9f.png">

**Comment by yedhink** [comment]
@vikas95prasad _a

I understand the error now.

The core underlying issue is that eslint's indent rule and prettier's indentation styles do not match - they're completely separate implementations and are two different approaches to solving the same problem. Thus if we use them together, then clashes can lead to above errors.

Rather than overriding each of the rules, like you have done in your PR, let's make use of the already existing config to handle these clashes for us, by giving priority to prettier formatting.

Just update the `.eslintrc.js` config's `extends` key with the following and it should work:
```json
"extends": [
    "plugin:json/recommended",
    "eslint:recommended",
    "plugin:react/recommended",
    "prettier"
],
```

You can update your PR with the same and assign me the PR once done.

**Comment by yedhink** [comment]
@vikas95prasad 

On a separate note, maintaining nested ternaries, like you done in the above mentioned example code, is not that readable and can be harder to debug. Prefer proper if/else or switch for these nested conditionals.

Length/Number of lines of a function is always second priority when comparing to readability criteria.

**Comment by vikas95prasad** [comment]
> @vikas95prasad
> 
> On a separate note, maintaining nested ternaries, like you done in the above mentioned example code, is not that readable and can be harder to debug. Prefer proper if/else or switch for these nested conditionals.
> 
> Length/Number of lines of a function is always second priority when comparing to readability criteria.

@yedhink 

I thought of adding it in the example that, this code is just to help you reproduce the bug. Anyways,

I do understand that lengthly nested ternaries are not recommended. The above example was written to help you reproduce the bug.
