### ISSUE TITLE
Add ternary operator multiline support

### ISSUE THREAD

**Issue by Harshit-frontend** [bigbinary/wheel#617]
Currently, the system doesn't allow us to use a multiline ternary operator. 

Below is the real-time example.

<img width="540" alt="Screenshot 1943-06-31 at 12 57 58 PM" src="https://user-images.githubusercontent.com/83356733/134300885-2a375c8b-f632-4a37-b475-034116e2ebef.png">

cc @yedhink

**Comment by yedhink** [comment]
@Harshit-frontend 

The current rules allow multiline ternary operators. It raises issues only when overly exploiting the ternary operator or more specifically when a deep nesting pattern is followed.

Please note that `multiline ternary operators` and `nested ternary operators` are not the same thing.

The code that is shown in the screenshot is really hard to debug. And allowing developers to write such nested ternary code is a bad choice in the long run. It affects readability and clearness of code and paves the way to a potential mistake through the insufficient understanding of the nesting itself.

The code shown in the above code is a perfect use case for `if-elseif-else` statement or even better the `switch` statement with a `default` case, and it would have improved the readability too.

Currently closing this issue, since the rules are working as intended. If there are any other specific examples where this rule is potentially giving false positives, then please feel free to re-open this issue with relevant screenshots+link to code(if possible).

Thanks.

**Comment by Harshit-frontend** [comment]
What can be the possible solution in this case?

<img width="706" alt="Screenshot 1943-06-31 at 3 07 57 PM" src="https://user-images.githubusercontent.com/83356733/134320429-c10ef83c-f68d-4692-81aa-fb5f91cad344.png">

**Comment by yedhink** [comment]
@Harshit-frontend For logical expressions, it is a false positive case and our eslint config needs to be updated. I will fix this in wheel. Once you pull the latest from wheel after that, this issue won't show up for Logical expressions.

Thanks for pointing this out. Appreciate it a lot. Anytime you face issues with any configs from wheel, feel free to raise an issue and mention me in it.
