### ISSUE TITLE
Add new eslint rule for hooks: react-hooks/exhaustive-deps

### ISSUE THREAD

**Issue by sangameshsomawar** [bigbinary/wheel#705]
With reference to the suggestion:
https://github.com/bigbinary/neeto-invoice-rn/pull/100#issuecomment-958312831

Other References:
https://reactjs.org/docs/hooks-rules.html
https://stackoverflow.com/questions/58866796/understanding-the-react-hooks-exhaustive-deps-lint-rule

neetoInvoice:
https://github.com/bigbinary/neeto-invoice-rn/pull/100

**Comment by Harshit-frontend** [comment]
Following rule has to be considered inside `warning` instead of an `error`. As it will cause unnecessary rendering. Let the developer handle this.

 "react-hooks/exhaustive-deps": "error",

**Comment by yedhink** [comment]
@Harshit-frontend Please open a new issue. Please don't reopen issues which have been closed as part of merging a PR.

In the new issue, please put up a video on what advantage does keeping this rule as `warn` over `error` provides to the developer and from a pipeline perspective.

> As it will cause unnecessary rendering. Let the developer handle this.

Yes. In order to make sure the developer will handle it, we have set it as `error` rather than `warn`. Warnings can be ignored by developers whereas `errors` have to be fixed.

**Comment by Harshit-frontend** [comment]
> @Harshit-frontend Please open a new issue. Please don't reopen issues which have been closed as part of merging a PR.
> 
> In the new issue, please put up a video on what advantage does keeping this rule as `warn` over `error` provides to the developer and from a pipeline perspective.
> 
> > As it will cause unnecessary rendering. Let the developer handle this.
> 
> Yes. In order to make sure the developer will handle it, we have set it as `error` rather than `warn`. Warnings can be ignored by developers whereas `errors` have to be fixed.

Created an [issue](https://github.com/bigbinary/wheel/issues/712) for the same.
