### ISSUE TITLE
Consider eslint rule for hooks: react-hooks/exhaustive-dep as warn instead of error.

### ISSUE THREAD

**Issue by Harshit-frontend** [bigbinary/wheel#712]
https://www.loom.com/share/2856a0e771bc45398687e248144c3539

**Comment by Harshit-frontend** [comment]
Conversation over [here](https://github.com/facebook/create-react-app/issues/6880#issuecomment-485936545) can help us in understanding the negative impact of using this as an error.

**Comment by yedhink** [comment]
@Harshit-frontend _a

Very valid point.

Can you please make a PR for this? Just update the existing rule to `warn`.

cc: @sangameshsomawar This is the edge case that I was talking about. Had encountered something similar in the past too. Say if we are using `react-router-dom` history prop within the `useEffect`, then it often leads to infinite loops too.

**Comment by sangameshsomawar** [comment]
@yedhink @Harshit-frontend :

I am fine with reverting the change and making the rule a warning. 
I also agree that many people started facing issues with the rule.

But as I said earlier, This rule is really helpful, improves performance, and helps us detect many bugs in advance.

Let's understand with the below video,

https://www.loom.com/share/42e7a89f32c141db90db98a7a13c7c85

**Comment by vishnu-m** [comment]
@sangameshsomawar Thanks for the detailed video. I was facing some issues after this rule was added and was going through many resources on the same. This was helpful.

**Comment by yedhink** [comment]
@sangameshsomawar Thanks for the detailed video.

Agree that this is a useful rule. But the core underlying issue lies in the fact that most of the neeto repos have already got bad code merged into them. These eslint rules and the enforcement started only a few months back in neeto side. [Refer](https://github.com/bigbinary/wheel/pull/619).

So let's take [this PR](https://github.com/bigbinary/neeto-auth-web/pull/729) in neetoAuth. The person making the changes intended only to make some UI updates. But Eslint flagged a lot of `exhaustive-deps` offenses because the already existing code had these offenses. So if we had set this rule as `error`, then it would have been a blocker for the UI person. Currently, as we have set this as `warn`, and CI is passing.

I agree that it's not the best way to do it. So let's take baby steps inorder to enforce this rule as an `error` itself.

- First, we need to write a bit about this rule - you have done a great job with the video
- Thus start by adding a new chapter in https://www.bigbinary.com/react-best-practices
- I will assign you an issue in https://github.com/bigbinary/bigbinary-website
- Once you make the PR, you can assign it to me

Let's get that merged. Once it's done, as the next step, let's see whether we can enforce this rule in each repo one by one and how much time will it take. The precursor for doing that is the documentation about useCallback as well as dependency array, both of which we will cover in react-best-practices.

**Comment by Harshit-frontend** [comment]
Using useCallback hook to a large extent can degrade the performance as it will never free up the memory space.

Check [this](https://kentcdodds.com/blog/usememo-and-usecallback#why-is-usecallback-worse) article

**Comment by vishnu-m** [comment]
Another article similar to the one Harshit specified - [link](https://dmitripavlutin.com/dont-overuse-react-usecallback/)

@sangameshsomawar Do we need to use the `useCallback` hook for the simple example you have given above? Is there any other way?
