### ISSUE TITLE
Normalize css repeat itself multiple times

### ISSUE THREAD

**Issue by Harshit-frontend** [bigbinary/wheel#732]
Across all **neetoProducts** I can see normalize CSS repeat itself multiple times. Please go through [this](https://www.loom.com/share/e19f078bcc4247e3a967c0c3ed1bfc68) video for more info.

cc @sandip-mane @yedhink @unnitallman

**Comment by sandip-mane** [comment]
Good find👍

**Comment by unnitallman** [comment]
@prasanthchaduvula _a

**Comment by praveen-murali-ind** [comment]
Related issue in neetoUI 👇

https://github.com/bigbinary/neeto-ui/issues/469

**Comment by unnitallman** [comment]
@praveen-murali-ind Please notify me once this is fixed. We will need to upgrade neeto UI on wheel and all the neeto apps once this is fixed

**Comment by praveen-murali-ind** [comment]
> @praveen-murali-ind Please notify me once this is fixed. We will need to upgrade neeto UI on wheel and all the neeto apps once this is fixed

Sure, will notify once this is fixed in neetoUI.

//cc @edwinbbu @karthiknmenon

**Comment by edwinbbu** [comment]
@edwinbbu _a Working on it.

**Comment by Harshit-frontend** [comment]
I am able to reproduce the issue. Thus, reopening it. Please go through [this](https://www.loom.com/share/5aa1ed1b52b046ee8238b7e0eb9afa05) video for more information

**Comment by edwinbbu** [comment]
@Harshit-frontend _a, In order to fix the issue, the neetoui version has to be updated to the latest version. neetoui version is updated in `wheel` and in `neeto-codify` repo. Please check these 2 places and see if you can reproduce the issue.

Please refer to PR https://github.com/bigbinary/neeto-ui/pull/665 and the recording I have in order to update to the latest neetoui version. 

Feel free to close the issue if you are satisfied. Let you know if you facing any issues.

**Comment by Harshit-frontend** [comment]
@edwinbbu Thanks for the information. 
I can see the current neetoui version is 3.0.1 in wheel but the folder name is v2 inside neetoui. I believe we need to update this one to v3.

**Comment by edwinbbu** [comment]
@Harshit-frontend There is no folder name change. The reason for the change to v3 is because v3 has breaking changes.
