### ISSUE TITLE
Remove no-nested-ternary rule

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/wheel#826]
Continuation of https://github.com/bigbinary/neeto-chat-web/pull/3302#discussion_r852596617
Add any comments additional comments here

**Comment by yedhink** [comment]
@Amaljith-K I understand the case you are making. I wish every tech lead or person who reviews PR is on the same page on making the call on when to allow nested ternary and when not to.

The primary reason for adding this rule is because of people abusing nested ternary in our codebases. Refer: https://github.com/bigbinary/wheel/issues/756#issue-1096007937

@karthiknmenon We can make this rule a warning. But I guess we will have write about this in our React Best Practices Book and ensure that all tech leads go through it.

@Amaljith-K Would you be able to point out some general guidelines on when you've felt nesting should be allowed? I see that generally you are pointing out nesting should be allowed in certain cases in JSX. If that's the case, then would you be able to please point cases where nesting shouldn't be allowed within JSX? Or is it like allow any number of nesting in JSX but not when writing JavaScript(non-JSX) code.

**Comment by Amaljith-K** [comment]
The most common case will be:
```jsx
{isItemsLoading ? (
  <PageLoader />
) : items.length === 0 ? (
  <NoItemsFound />
) : (
  items.map(item => <Item {...item} />)
)}
```

Let me think of a general guideline and get back to this later.

**Comment by Amaljith-K** [comment]
In plain javascript, we can create new variables and assign values wherever we want. So nested ternary should be minimized in it. The code will almost always look better with new variables than nested ternaries.

But in the case of JSX, defining new variables in between isn't possible. If we needed a variable, we should define it before the JSX even starts. 
Nested ternaries comes in handy in conditions where we need to code an if else ladder in JSX. One example is mentioned in the previous comment. Here is another example:
```jsx
<SomeParentComponent>
  {typeIs(SINGLE_CHOICE) ? (
    <SingleChoiceQuestion />
  ) : typeIs(MULTI_CHOICE) ? (
    <MultiChoiceQuestion />
  ) : typeIs(SHORT_ANSWER) ? (
    <ShortAnswerQuestion />
  ) : null}
</SomeParentComponent>
```

To avoid nested ternaries in JSX, either we will need to code a piece of JSX in plain JS section and use it inside the actual JSX. I've seen people follow tricky approaches like this:

```jsx
<SomeParentComponent>
  {isItemsLoading ? (
    <PageLoader />
  ) : (
    <>
      {isEmpty(items) ? (
        <NoItemsFound />
      ) : (
        items.map(item => <Item {...item} />)
      )}
    </>
</SomeParentComponent>
```

Defining a piece of JSX outside the actual JSX content as a new variable will also make code difficult to read. The reader will need to frequently switch between contexts.

As a general rule of thumb, nested ternaries can be used in JSX if it improves the code readability in comparison with other approaches. It should not be used in plain JS unless there is some exceptional case that demands it.

@yedhink _a

**Comment by neerajdotname** [comment]
My take would be to not to add this rule and rely on educating users when to use nested ternary operation and when not to use it.
